[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deap>=1.4.1",
    "fastapi[standard]>=0.115.4",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
]
